project:
  type: website

website:
  title: "SSN Data Vis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - entries.qmd
      - about.qmd
margin-header: |
  ![](/images/ANU_Primary_Horizontal_GoldBlack.png)
format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



